// app/add_images.jsx
import React from 'react';
import Dialog from 'material-ui/Dialog';
import FlatButton from 'material-ui/FlatButton';
import RaisedButton from 'material-ui/RaisedButton';
import Dropzone from 'react-dropzone'

import muiThemeable from 'material-ui/styles/muiThemeable'

import Avatar from 'material-ui/Avatar';
import IconPaste from 'material-ui/svg-icons/content/content-paste';

const myURL = window.URL || window.webkitURL
const AddImages = (props, context ) => {

  const addPicsFromForm = (event) => {
    for (let i = 0; i < event.target.files.length; i++) {
      console.log("files:", event.target.files[i])
      if (!event.target.files[i].type.match(/image.*/)) {
        alert("Could not add " + file.name + " because it it not a valid file.")
        continue
      }
      processPic(event.target.files[i])
    }
    props.close()
  }

  const processPic = (pic) => {
    const source = myURL.createObjectURL(pic)
    context.addFile(pic.name, source)
  }  

  const addPicsFromDrop = (files) => {
    files.forEach( file => {
      processPic(file)
    })
    props.close()
  }

  const actions = [
    <FlatButton
      label="Or Choose Files"
      labelPosition="before"
    >
      <input type="file" style={{
          cursor: 'pointer',
          position: 'absolute',
          top: 0,
          bottom: 0,
          right: 0,
          left: 0,
          width: '100%',
          height: '100%',
          opacity: 0,
        }} multiple onChange={ addPicsFromForm } />
    </FlatButton>
  ]
  // const inststr = (context.images.length > 0) ? "There are three options to add image files:"
  const titlestr = (context.images.length > 0) ? "Add More Images" : "Add Images"
  return (
      <Dialog
        title={titlestr}
        // actions={actions}
        modal={false}
        open={props.open}
        onRequestClose={props.close}
      >
        <h2 style={{textAlign: 'center'}}> There are three options to add image files: </h2>

        <div style={{ width: '30%', float: 'left', textAlign: 'center', marginRight: '4.9%'}}>
          <h4> Paste an image from your clipboard </h4>
          <div>
            <Avatar
              backgroundColor={props.muiTheme.palette.primary2Color}
              style={{marginTop: '35px'}}
              size={100}
              icon={<IconPaste />}
              />
          </div>
        </div>
        <div style={{ width: '30%', float: 'left', textAlign: 'center', marginRight: '4.9%'}}>
          <h4> Drag 'n Drop </h4>
          <Dropzone onDrop={addPicsFromDrop}
            style={{
              color: props.muiTheme.palette.primary2Color,
              fontSize: '40px',
              paddingTop: '40px',
              paddingBottom: '40px',
              lineHeight: '40px',
              borderRadius: '10px',
              border: `dashed ${props.muiTheme.palette.primary2Color} 2px`
            }}>
            DROP<br/>FILES<br/>HERE
          </Dropzone>
        </div>
        <div style={{ width: '30%', float: 'left', textAlign: 'center'}}>
          <h4> Select an image from your local machine </h4>
          <div>
            <FlatButton
              labelPosition="before"
              backgroundColor={props.muiTheme.palette.primary2Color}
              hoverColor={props.muiTheme.palette.primary3Color}
              style={{
                color: 'white',
                padding: '0.5em',
                marginTop: '45px',
                fontSize: '1.5em',
                height: '4em',
                borderRadius: '0.25em'
              }}
            >
              SELECT <br/>
              FILES
              <input type="file" style={{
                  cursor: 'pointer',
                  position: 'absolute',
                  top: 0,
                  bottom: 0,
                  right: 0,
                  left: 0,
                  width: '100%',
                  height: '100%',
                  opacity: 0,
                }} multiple onChange={ addPicsFromForm } />
            </FlatButton>
          </div>
        </div>
      </Dialog>
  )
}

AddImages.contextTypes = {
  addFile: React.PropTypes.func.isRequired,
  images: React.PropTypes.array.isRequired,
}


export default muiThemeable()(AddImages)

// app/AddImages.vue
<template>
  <div v-if="open" class="dialog-overlay" @click="close">
    <div class="dialog" @click.stop>
      <div class="dialog-header">
        <h2>{{ title }}</h2>
        <button class="close-button" @click="close">×</button>
      </div>
      <div class="dialog-content">
        <h2 class="instructions">There are three options to add image files:</h2>
        
        <div class="options-container">
          <div class="option">
            <h4>Paste an image from your clipboard</h4>
            <div class="option-icon">
              <div class="avatar-large">📋</div>
            </div>
          </div>
          
          <div 
            class="option dropzone"
            :class="{ 'drag-over': isDragOver }"
            @drop="handleDrop"
            @dragover.prevent="isDragOver = true"
            @dragleave="isDragOver = false"
            @click="triggerFileInput"
          >
            <h4>Drag 'n Drop</h4>
            <div class="dropzone-content">
              DROP<br/>FILES<br/>HERE
            </div>
          </div>
          
          <div class="option">
            <h4>Select an image from your local machine</h4>
            <button class="select-button" @click="triggerFileInput">
              SELECT<br/>FILES
            </button>
          </div>
        </div>
        
        <input 
          ref="fileInput"
          type="file" 
          multiple 
          accept="image/*"
          style="display: none" 
          @change="handleFileSelect" 
        />
      </div>
    </div>
  </div>
</template>

<script>
import { ref, computed, inject } from 'vue'

const myURL = window.URL || window.webkitURL

export default {
  name: 'AddImages',
  props: {
    open: {
      type: Boolean,
      required: true
    }
  },
  emits: ['close'],
  setup(props, { emit }) {
    const fileInput = ref(null)
    const isDragOver = ref(false)
    const images = inject('images')
    const addFile = inject('addFile')

    const title = computed(() => {
      return images.value.length > 0 ? 'Add More Images' : 'Add Images'
    })

    const processPic = (pic) => {
      const source = myURL.createObjectURL(pic)
      addFile(pic.name, source)
    }

    const handleFileSelect = (event) => {
      for (let i = 0; i < event.target.files.length; i++) {
        const file = event.target.files[i]
        if (!file.type.match(/image.*/)) {
          alert(`Could not add ${file.name} because it is not a valid image file.`)
          continue
        }
        processPic(file)
      }
      emit('close')
      if (fileInput.value) {
        fileInput.value.value = ''
      }
    }

    const handleDrop = (event) => {
      event.preventDefault()
      isDragOver.value = false
      const files = Array.from(event.dataTransfer.files)
      files.forEach((file) => {
        if (file.type.match(/image.*/)) {
          processPic(file)
        } else {
          alert(`Could not add ${file.name} because it is not a valid image file.`)
        }
      })
      emit('close')
    }

    const triggerFileInput = () => {
      if (fileInput.value) {
        fileInput.value.click()
      }
    }

    const close = () => {
      emit('close')
    }

    return {
      fileInput,
      isDragOver,
      title,
      handleFileSelect,
      handleDrop,
      triggerFileInput,
      close
    }
  }
}
</script>

<style scoped>
.dialog-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.dialog {
  background: white;
  border-radius: 4px;
  max-width: 90%;
  width: 800px;
  max-height: 90vh;
  overflow-y: auto;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
}

.dialog-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5em;
  border-bottom: 1px solid #e0e0e0;
}

.dialog-header h2 {
  margin: 0;
  font-size: 1.5em;
  font-weight: 400;
}

.close-button {
  background: none;
  border: none;
  font-size: 2em;
  cursor: pointer;
  color: #666;
  line-height: 1;
  padding: 0;
  width: 32px;
  height: 32px;
}

.close-button:hover {
  color: #000;
}

.dialog-content {
  padding: 2em;
}

.instructions {
  text-align: center;
  margin-bottom: 2em;
  font-size: 1.2em;
}

.options-container {
  display: flex;
  gap: 2%;
  justify-content: space-between;
}

.option {
  flex: 1;
  text-align: center;
  padding: 1em;
}

.option h4 {
  margin: 0 0 1em 0;
  font-size: 1em;
  font-weight: 500;
}

.avatar-large {
  width: 100px;
  height: 100px;
  border-radius: 50%;
  background-color: #2F6A90;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 3em;
  margin: 35px auto 0;
}

.dropzone {
  border: dashed #2F6A90 2px;
  border-radius: 10px;
  padding: 40px;
  cursor: pointer;
  transition: all 0.2s;
}

.dropzone.drag-over {
  background-color: rgba(47, 106, 144, 0.1);
  border-color: #153C54;
}

.dropzone-content {
  color: #2F6A90;
  font-size: 40px;
  line-height: 1.2;
  padding-top: 40px;
  padding-bottom: 40px;
}

.select-button {
  background-color: #2F6A90;
  color: white;
  border: none;
  padding: 1.5em;
  margin-top: 45px;
  font-size: 1.5em;
  height: 4em;
  border-radius: 0.25em;
  cursor: pointer;
  transition: background-color 0.2s;
  line-height: 1.2;
}

.select-button:hover {
  background-color: #1f4a6a;
}
</style>
