// app/App.vue
<template>
  <Wrapper>
    <AddImages 
      :open="imagesDialogOpen" 
      @close="closeAddImages" 
    />
    <Display 
      :settings="settings" 
      :canvas="canvas" 
    />
  </Wrapper>
</template>

<script>
import { ref, computed, onMounted, provide } from 'vue'
import Wrapper from './Wrapper.vue'
import Display from './Display.vue'
import AddImages from './AddImages.vue'
import saveAs from 'file-saver'

const canvas = document.createElement('canvas')
let pastedCount = 0

export default {
  name: 'App',
  components: {
    Wrapper,
    Display,
    AddImages
  },
  setup() {
    const imagesDialogOpen = ref(false)
    const images = ref([])
    const color = ref('#ffffff')
    const margin = ref(10)
    const direction = ref('vertical')

    const newImage = (source) => {
      const img = new Image()
      img.onload = function() {
        this.setAttribute('rel', 'loaded')
        console.log('image size:', this.width, this.height)
      }
      img.src = source
      return img
    }

    const addFile = (name, source) => {
      const file = {
        name: name,
        image: newImage(source)
      }
      images.value.push(file)
    }

    const moveFile = (idx, delta) => {
      const curFiles = [...images.value]
      ;[curFiles[idx], curFiles[idx + delta]] = [curFiles[idx + delta], curFiles[idx]]
      images.value = curFiles
    }

    const rotateImage = (idx, deg) => {
      const img = images.value[idx]
      const tmpCanvas = document.createElement('canvas')
      tmpCanvas.width = img.image.height
      tmpCanvas.height = img.image.width
      const ctx = tmpCanvas.getContext('2d')
      ctx.translate(tmpCanvas.width / 2, tmpCanvas.height / 2)
      ctx.rotate((deg * Math.PI) / 180)
      ctx.drawImage(img.image, -img.image.width / 2, -img.image.height / 2)
      img.image = newImage(tmpCanvas.toDataURL('image/png'))
      const curFiles = [...images.value]
      curFiles[idx] = img
      images.value = curFiles
    }

    const removeFile = (idx) => {
      const files = [...images.value]
      files.splice(idx, 1)
      images.value = files
    }

    const setDirection = (dir) => {
      direction.value = dir
    }

    const setMargin = (m) => {
      margin.value = m
    }

    const setColor = (c) => {
      color.value = c
    }

    const saveImage = () => {
      canvas.toBlob((blob) => {
        saveAs(blob, `photostrip-${direction.value}-${images.value.length}.png`)
      })
    }

    const openAddImages = () => {
      imagesDialogOpen.value = true
    }

    const closeAddImages = () => {
      imagesDialogOpen.value = false
    }

    const settings = computed(() => ({
      images: images.value,
      color: color.value,
      margin: margin.value,
      direction: direction.value
    }))

    // Handle paste events
    document.onpaste = (event) => {
      const items = (event.clipboardData || event.originalEvent.clipboardData).items
      Object.keys(items).forEach((index) => {
        const item = items[index]
        if (item.kind === 'file') {
          const blob = item.getAsFile()
          const reader = new FileReader()
          reader.onload = (e) => {
            addFile(`Pasted Image #${++pastedCount}`, e.target.result)
          }
          reader.readAsDataURL(blob)
        }
      })
    }

    // Provide context to child components
    provide('images', images)
    provide('direction', direction)
    provide('margin', margin)
    provide('color', color)
    provide('canvas', canvas)
    provide('addFile', addFile)
    provide('moveFile', moveFile)
    provide('removeFile', removeFile)
    provide('rotateImage', rotateImage)
    provide('setDirection', setDirection)
    provide('setMargin', setMargin)
    provide('setColor', setColor)
    provide('saveImage', saveImage)
    provide('openAddImages', openAddImages)

    onMounted(() => {
      if (images.value.length === 0) {
        imagesDialogOpen.value = true
      }
    })

    return {
      imagesDialogOpen,
      images,
      color,
      margin,
      direction,
      canvas,
      settings,
      closeAddImages
    }
  }
}
</script>

// app/app.jsx

import React from 'react'
import { render } from 'react-dom'
import {RadioButton, RadioButtonGroup} from 'material-ui/RadioButton';
import Slider from 'material-ui/Slider';
import Subheader from 'material-ui/Subheader';
import { TwitterPicker } from 'react-color';
import saveAs from 'file-saver';

import Wrapper from './wrapper'
import Files from './files'
import Display from './display'
import AddImages from './add_images'
// import ImagePaster from './image_paster'

const canvas = document.createElement('canvas')
let pastedCount = 0

class App extends React.Component {

    constructor(props) {
        super(props);
        
        this.state = {
            imagesDialogOpen: false,
            images: [],
            color: "#ffffff",
            margin: 10,
            direction: "vertical",
        }

        this.constructor.childContextTypes = {
            images: React.PropTypes.array,
            direction: React.PropTypes.string,
            margin: React.PropTypes.number,
            color: React.PropTypes.string,
            canvas: React.PropTypes.object,

            addFile: React.PropTypes.func,
            moveFile: React.PropTypes.func,
            removeFile: React.PropTypes.func,
            rotateImage: React.PropTypes.func,
            setDirection: React.PropTypes.func,
            setMargin: React.PropTypes.func,
            setColor: React.PropTypes.func,
            saveImage: React.PropTypes.func,
            openAddImages: React.PropTypes.func,
        }

        this.onChange = this.onChange.bind(this)
        this.marginChange = this.marginChange.bind(this)
        this.colorChange = this.colorChange.bind(this)
        this.addFile = this.addFile.bind(this)
        this.moveFile = this.moveFile.bind(this)
        this.removeFile = this.removeFile.bind(this)
        this.rotateImage = this.rotateImage.bind(this)
        this.setDirection = this.setDirection.bind(this)
        this.setMargin = this.setMargin.bind(this)
        this.setColor = this.setColor.bind(this)
        this.saveImage = this.saveImage.bind(this)
        this.openAddImages = this.openAddImages.bind(this)
        this.closeAddImages = this.closeAddImages.bind(this)

        document.onpaste = (event) => {
            var items = (event.clipboardData || event.originalEvent.clipboardData).items;
            Object.keys(items).forEach((index) => {
                var item = items[index];
                if (item.kind === 'file') {
                    var blob = item.getAsFile();
                    var reader = new FileReader();
                    reader.onload = (event) => {
                        this.addFile(`Pasted Image #${++pastedCount}`, event.target.result)   
                    }
                    reader.readAsDataURL(blob);
                }
            })
        }


    }

    getChildContext() {
        return {
            images: this.state.images,
            direction: this.state.direction,
            margin: this.state.margin,
            color: this.state.color,
            canvas: canvas,

            addFile: this.addFile,
            moveFile: this.moveFile,
            removeFile: this.removeFile,
            rotateImage: this.rotateImage,
            setDirection: this.setDirection,
            setMargin: this.setMargin,
            setColor: this.setColor,
            saveImage: this.saveImage,
            openAddImages: this.openAddImages,
        }
    }

    openAddImages() {
        this.setState({imagesDialogOpen: true})
    }

    closeAddImages() {
        this.setState({imagesDialogOpen: false})
    }

    onChange(event, value) {
        let newState = {}
        newState[event.target.name] = value
        this.setState(newState)
    }

    setDirection(direction) {
        this.setState({direction: direction})
    }

    setMargin(margin) {
        this.setState({margin: margin})
    }

    setColor(color) {
        this.setState({color: color})
    }

    marginChange(event, value) {
        let newState = {
            margin: value
        }
        this.setState(newState)
    }

    newImage(source) {
        let img = new Image()
        img.onload = function() {
            this.setAttribute("rel", "loaded")
            console.log("image size:", this.width, this.height)
        }
        img.src = source
        return img
    }

    addFile(name, source) {
        let file = {
            name: name,
            image: this.newImage(source),

        }

        let curFiles = this.state.images
        curFiles.push(file)
        this.setState({images: curFiles})
    }

    moveFile(idx, delta) {
        let curFiles = this.state.images;
        [curFiles[idx], curFiles[idx+delta]] = [curFiles[idx+delta], curFiles[idx]]
        this.setState({images: curFiles})
    }

    rotateImage(idx, deg) {
        let img = this.state.images[idx]
        let tmpCanvas = document.createElement('canvas')
        tmpCanvas.width = img.image.height
        tmpCanvas.height = img.image.width
        const ctx = tmpCanvas.getContext('2d')
        ctx.translate(tmpCanvas.width/2,tmpCanvas.height/2)
        ctx.rotate(deg*Math.PI/180)
        ctx.drawImage(img.image,-img.image.width/2,-img.image.height/2)
        img.image = this.newImage(tmpCanvas.toDataURL('image/png'))
        let curFiles = this.state.images
        curFiles[idx] = img
        this.setState({images: curFiles})
    }

    removeFile(idx) {
        let files = this.state.images;
        files.splice(idx, 1)
        this.setState({images: files})
    }

    colorChange(color) {
        this.setState({ color: color.hex })
        this.forceUpdate()
    }

    saveImage(event) {
        canvas.toBlob((blob) => {
            saveAs(blob, "photostrip-" + this.state.direction + "-" + this.state.images.length + ".png");
        });
    }

    componentWillMount() {
        if(this.state.images.length == 0) {
            this.setState({imagesDialogOpen: true})
        }
    }

    render() {
        return (
            <Wrapper images={this.state.images} >
                <AddImages open={this.state.imagesDialogOpen} close={this.closeAddImages} />
                <Display settings={this.state} canvas={canvas} />
            </Wrapper>
            )
    }

}

window.initiatePhotoStitch = function(ele) {
    render(
        <App />,
        ele
    )
}
